version: '0.0.1'

services:
  neo4j:
    image: neo4j:5.14.0
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - n4jdata:/data
      - n4jlogs:/logs
    environment:
      # Raise memory limits
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/password

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rags:latest
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - neo4j
    ports:
      - 4000:4000

volumes:
  n4jdata:
  n4jlogs:
